### ISSUE TITLE
Sometimes getParagraphs(1) returns array('')

### ISSUE THREAD

**Issue by arvidj** [Badcow/LoremIpsum#1]
Seems to happen with `srand(1428581280)` after 35 iterations.

**Comment by samuelwilliams** [comment]
I have managed to replicate the issue you have described. There's a new branch called `issue1` with a test case https://github.com/Badcow/LoremIpsum/blob/issue1/lib/Tests/Github/Issue_01_Test.php

I did not manage to replicate as you described with `srand(1428581280)`, but this may be a system dependent anomaly.

Thanks for the issue, it was about time I wrote tests for the suite!

**Comment by samuelwilliams** [comment]
Fails because the number of sentences that the `getParagraphs` method calls for can be less than zero in some cases. This is because the number returned by the gaussian can be less than zero.

**Comment by samuelwilliams** [comment]
This is now fixed.

**Comment by arvidj** [comment]
Hi, thanks for a quick fix!
